# Generated by Django 3.0.5 on 2020-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
